name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION

categories:
  - title: 🚀 New features and improvements
    labels:
      - enhancement
  - title: 🔧 Hardware changes
    labels:
      - hardware
  - title: 🐛 Bug Fixes
    labels:
      - bug
  - title: 🎛️ Adjustments
    labels:
      - adjustment
  - title: 🚦 Internal changes
    labels:
      - internal

exclude-labels:
  - no-changelog
  - duplicate
  - invalid
  - wontfix

template: |
    $CHANGES
