services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - 1885:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  wokwi:
    image: wokwi/wokwi-ci-server
    platform: linux/amd64
    ports:
      - "9177:3000"
