name: CI Build
on:
  push:
  release:
    types: [published]

env:
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_MAXSIZE: 256M
  CCACHE_COMPRESS: true
  ESP_IDF_VERSION: v5.5

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - environment: mk5-release
            ud_gen: MK5
            ud_debug: 0
            target: esp32s3
          - environment: mk6-release
            ud_gen: MK6
            ud_debug: 0
            target: esp32s3
          - environment: mk7-release
            ud_gen: MK7
            ud_debug: 0
            target: esp32s3
          - environment: mk8-release
            ud_gen: MK8
            ud_debug: 0
            target: esp32s3

          # Debug variant
          - environment: mk6-debug
            ud_gen: MK6
            ud_debug: 1
            target: esp32s3

          # Future release with ESP32-C6
          - environment: mkX-release
            ud_gen: MKX
            ud_debug: 0
            target: esp32c6

    env:
      # Enable verbose logging in debug artifacts for farmhub tags
      FARMHUB_LOG_VERBOSE: env,scheduling

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.ESP_IDF_VERSION }}-${{ matrix.environment }}

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          esp_idf_docker_image: lptr/esp-idf-clang
          target: ${{ matrix.target }}
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            idf.py build -DUD_GEN=${{ matrix.ud_gen }} -DUD_DEBUG=${{ matrix.ud_debug }} -DFARMHUB_LOG_VERBOSE=${{ env.FARMHUB_LOG_VERBOSE }} && \
            ccache -s

      - name: clang-tidy
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          esp_idf_docker_image: lptr/esp-idf-clang
          target: ${{ matrix.target }}
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            ./generate-clang-tidy-compile-db.py && \
            clang-tidy -p build/clang-tidy $(find main components -type f -name '*.cpp' -not -path '*/test/*' -not -path '*/build/*')

      - name: Rename firmware artifact
        run: |
          cp build/ugly-duckling.bin ugly-duckling-${{ matrix.environment }}.bin

      - name: Create debug artifact
        run: |
          zip debug-${{ matrix.environment }}.zip \
            build/project_description.json \
            build/*.bin \
            build/*.elf \
            build/*.map \
            build/config/sdkconfig.h

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ugly-duckling-${{ matrix.environment }}
          path: |
            ugly-duckling-${{ matrix.environment }}.bin
            debug-${{ matrix.environment }}.zip
          if-no-files-found: error

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.ESP_IDF_VERSION }}-unit-test

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32s3
          path: test/unit-tests
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            idf.py build && \
            ccache -s

      - name: Run a Wokwi CI server
        uses: wokwi/wokwi-ci-server-action@v1

      - name: esp-idf test
        run: |
            docker run \
            -v .:/project \
            -v ./artifacts/pytest-logs:/logs \
            -w /project/test/unit-tests \
            -e HOME=/tmp \
            -e WOKWI_CLI_TOKEN=${{ secrets.WOKWI_CLI_TOKEN }} \
            lptr/pytest-embedded:latest \
            pytest \
              --embedded-services idf,wokwi \
              --root-logdir /logs \
              ./pytest_unit-tests.py \
              --wokwi-timeout=120000

      - name: Upload pytest-embedded logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-embedded-logs
          path: |
            artifacts/pytest-logs/**
          if-no-files-found: warn

  integ-test:
    runs-on: ubuntu-latest

    env:
      HOSTNAME: ""

    steps:
      - uses: actions/checkout@v5

      - name: Start Mosquitto
        uses: namoshek/mosquitto-github-action@v1
        with:
          ports: '1883:1883'
          config: ${{ github.workspace }}/.github/mosquitto/mosquitto.conf

      - name: Get Host IP
        run: |
          HOSTNAME=$(hostname -I | awk '{print $1}')
          echo "HOSTNAME=$HOSTNAME" >> $GITHUB_ENV

      - name: Restore ccache cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ env.ESP_IDF_VERSION }}-integ-test

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: ${{ env.ESP_IDF_VERSION }}
          target: esp32s3
          path: test/integ-tests
          extra_docker_args: -v  ${{ env.CCACHE_DIR }}:/root/.ccache
          command: |
            ccache --max-size=${{ env.CCACHE_MAXSIZE }} && \
            idf.py -DUD_GEN=MK6 -DUD_DEBUG=1 -DFSUPLOAD=1 -DWOKWI=1 -DWOKWI_MQTT_HOST=${{ env.HOSTNAME }} build && \
            ccache -s

      - name: Run a Wokwi CI server
        uses: wokwi/wokwi-ci-server-action@v1

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          path: test/integ-tests
          timeout: 30000
          expect_text: 'Device ready'
          serial_log_file: 'log-hello-world.txt'

      # - name: esp-idf test
      #   run: |
      #     docker run -v .:/project -w /project/test/integ-tests -e HOME=/tmp -e WOKWI_CLI_TOKEN=${{ secrets.WOKWI_CLI_TOKEN }} lptr/pytest-embedded:latest pytest --embedded-services idf,wokwi ./pytest_integ-tests.py

  pages:
    name: Publish OTA to GitHub Pages
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      RETENTION_DAYS: 30
      TARGET_DIR: snapshots

    steps:
      - name: Checkout source
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download workflow artifacts
        uses: actions/download-artifact@v5
        with:
          path: work/artifacts

      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: work/site
          fetch-depth: 0

      - name: Adjust env for release runs
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          echo "RETENTION_DAYS=0" >> $GITHUB_ENV
          echo "TARGET_DIR=releases" >> $GITHUB_ENV

      - name: Run publisher
        run: |
          python3 .github/publish-ota.py \
            --artifacts work/artifacts \
            --site work/site/${{ env.TARGET_DIR }} \
            --base-url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.TARGET_DIR }}" \
            --retention-days "${{ env.RETENTION_DAYS }}" \
            --repo-root . \
            --commit-sha "${{ github.sha }}"
        shell: bash

      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: work/site
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
          commit_message: |
            OTA Pages: ${{ github.sha }} (retention: ${{ env.RETENTION_DAYS }} days)

  release:
    needs:
      - build
      - unit-test
      - integ-test
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: work/artifacts

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: AButler/upload-release-assets@v3.0
        with:
          files: work/artifacts/ugly-duckling-*/*
          repo-token: ${{ secrets.GITHUB_TOKEN }}
